version: '3.8'

services:
  sfu:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: odoo-sfu
    network_mode: "host"
    environment:
      - AUTH_KEY=$(grep AUTH_KEY .env | cut -d= -f2)
      - PUBLIC_IP=51.91.249.43
      - RTC_MIN_PORT=40000
      - RTC_MAX_PORT=49999
      - PROXY=1
      - LOG_LEVEL=info
    restart: unless-stopped
  