version: '3.8'

services:
  sfu:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: odoo-sfu
    environment:
      - DEBUG=*
      - NODE_DEBUG=*
      - AUTH_KEY=$(grep AUTH_KEY .env | cut -d= -f2)
      - PUBLIC_IP=51.91.249.43
    ports:
      - "8070:8070"
    # Override the command to get an interactive shell
    command: /bin/bash
    tty: true
    stdin_open: true